local function gap()
	sbar.add("item", { position = "right", width = 16, padding_left = 0, padding_right = 0 })
end

gap()
require("items.widgets.weather")
gap()
require("items.widgets.battery")
gap()
require("items.widgets.performance")
gap()
require("items.widgets.volume")
gap()
require("items.widgets.wifi")
gap()
require("items.widgets.bluetooth")
gap()
require("items.widgets.wallpaper")
gap()
require("items.widgets.media")
