-- Generated by matugen. Backgrounds and accents only: tokyonight keeps its own
-- syntax colours, so diagnostics and diffs stay readable.
return {
	bg = "{{colors.surface_container.default.hex}}",
	bg_dark = "{{colors.surface_container_low.default.hex}}",
	bg_float = "{{colors.surface_container_high.default.hex}}",
	bg_visual = "{{colors.primary_container.default.hex}}",
	fg_gutter = "{{colors.outline_variant.default.hex}}",
	border = "{{colors.outline.default.hex}}",
	primary = "{{colors.primary.default.hex}}",
	on_primary = "{{colors.on_primary.default.hex}}",
}
